title: "werdew's Reference"
description: Personal page & reference site
url: "https://werdew.github.io"

# Theme settings
theme: just-the-docs

color_scheme: light

# Search (Lunr.js – super fast)
search_enabled: true

# Mermaid Diagrams
mermaid:
  version: "11.4.0"

# GitHub edit button
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/werdew/werdew.github.io"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

# Footer
footer_content: "© werdew – Personal Page / Reference"
